dist: xenial
sudo: required
language: python
python:
  - '2.7'

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

before_install:
  - sudo apt-get update
  - cat install.txt | xargs sudo apt-get install -y

jobs:
  include:
    - stage: test
      install: pip install tox
      # Borrowed from flask-mongoengine
      script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
      # This adds a second parallel "test" stage (since we didn't specify
      # the stage name)
    - install: pip install -r requirements.txt
      script: mkdir statick_output; ./statick . statick_output --profile self_check.yaml
      # Force this to only run for one Python version
    - stage: build
      python: '2.7'
      install: pip install -r requirements-docs.txt
      script:
        - travis-sphinx build
    - stage: deploy
      # Force this to only run for one Python version
      python: '2.7'
      install: pip install -r requirements-docs.txt
      script:
        - travis-sphinx deploy
